const CampPageActionTypes = {
  SET_CURRENT_MISSION: "SET_CURRENT_MISSION",
  TOGGLE_MISSION_COMPLETE: "TOGGLE_MISSION_COMPLETE",
  TOGGLE_MISSION_PLANNED: "TOGGLE_MISSION_PLANNED",
  SET_AS_FRIEND: "SET_AS_FRIEND",
  SET_AS_ENEMY: "SET_AS_ENEMY",
  TOGGLE_ACTIVE: "TOGGLE_ACTIVE",
}

export default CampPageActionTypes
