const SheetActionTypes = {
  FETCH_CURRENT_SHEET_START: 'FETCH_CURRENT_SHEET_START',
  FETCH_CURRENT_SHEET_SUCCESS: 'FETCH_CURRENT_SHEET_SUCCESS',
  FETCH_CURRENT_SHEET_FAILURE: 'FETCH_CURRENT_SHEET_FAILURE',

  UPDATE_SHEET_START: 'UPDATE_SHEET_START',
  UPDATE_SHEET_SUCCESS: 'UPDATE_SHEET_SUCCESS',
  UPDATE_SHEET_FAILURE: 'UPDATE_SHEET_FAILURE',

  DELETE_SHEET_START: 'DELETE_SHEET_START',
  DELETE_SHEET_SUCCESS: 'DELETE_SHEET_SUCCESS',
  DELETE_SHEET_FAILURE: 'DELETE_SHEET_FAILURE',

  FETCH_SHEET_RESOURCES_START: 'FETCH_SHEET_RESOURCES_START',
  FETCH_SHEET_RESOURCES_SUCCESS: 'FETCH_SHEET_RESOURCES_SUCCESS',
  FETCH_SHEET_RESOURCES_FAILURE: 'FETCH_SHEET_RESOURCES_FAILURE',

  CREATE_SHEET_RESOURCE_START: 'CREATE_SHEET_RESOURCE_START',
  CREATE_SHEET_RESOURCE_SUCCESS: 'CREATE_SHEET_RESOURCE_SUCCESS',
  CREATE_SHEET_RESOURCE_FAILURE: 'CREATE_SHEET_RESOURCE_FAILURE',

  UPDATE_SHEET_RESOURCE_START: 'UPDATE_SHEET_RESOURCE_START',
  UPDATE_SHEET_RESOURCE_SUCCESS: 'UPDATE_SHEET_RESOURCE_SUCCESS',
  UPDATE_SHEET_RESOURCE_FAILURE: 'UPDATE_SHEET_RESOURCE_FAILURE',

  DELETE_SHEET_RESOURCE_START: 'DELETE_SHEET_RESOURCE_START',
  DELETE_SHEET_RESOURCE_SUCCESS: 'DELETE_SHEET_RESOURCE_SUCCESS',
  DELETE_SHEET_RESOURCE_FAILURE: 'DELETE_SHEET_RESOURCE_FAILURE',
};

export default SheetActionTypes;
