const CharPageActionTypes = {
  MAKE_A_CHECK: "MAKE_A_CHECK",
  EQUIP_WEAPON: "EQUIP_WEAPON",
  EQUIP_ITEM: "EQUIP_ITEM",
  EQUIP_WEARABLE: "EQUIP_WEARABLE",
  UNEQUIP_WEAPON: "UNEQUIP_WEAPON",
  UNEQUIP_ITEM: "UNEQUIP_ITEM",
  UNEQUIP_WEARABLE: "UNEQUIP_WEARABLE",
  PAY_OR_RECIEVE_MONEY: "PAY_OR_RECIEVE_MONEY",
  TAKE_OR_HEAL_DAMAGE: "TAKE_OR_HEAL_DAMAGE",
  CREATE_CHARACTER_LOG: "CREATE_CHARACTER_LOG",
  EDIT_CHARACTER_LOG: "EDIT_CHARACTER_LOG",
  LEVEL_UP: "LEVEL_UP",
  ADD_NEW_OR_EDIT_WEAPON: "ADD_NEW_OR_EDIT_WEAPON",
  ADD_NEW_OR_EDIT_ITEM: "ADD_NEW_OR_EDIT_ITEM",
  ADD_NEW_OR_EDIT_WEARABLE: "ADD_NEW_OR_EDIT_WEARABLE",
  SELL_INVENTORY_ITEM: "SELL_INVENTORY_ITEM",
  TAKE_A_REST: "TAKE_A_REST",
  ATTACK: "ATTACK",
}

export default CharPageActionTypes
