const CharacterActionTypes = {
  FETCH_CURRENT_CHARACTER_START: 'FETCH_CURRENT_CHARACTER_START',
  FETCH_CURRENT_CHARACTER_SUCCESS: 'FETCH_CURRENT_CHARACTER_SUCCESS',
  FETCH_CURRENT_CHARACTER_FAILURE: 'FETCH_CURRENT_CHARACTER_FAILURE',

  UPDATE_CHARACTER_START: 'UPDATE_CHARACTER_START',
  UPDATE_CHARACTER_SUCCESS: 'UPDATE_CHARACTER_SUCCESS',
  UPDATE_CHARACTER_FAILURE: 'UPDATE_CHARACTER_FAILURE',

  DELETE_CHARACTER_START: 'DELETE_CHARACTER_START',
  DELETE_CHARACTER_SUCCESS: 'DELETE_CHARACTER_SUCCESS',
  DELETE_CHARACTER_FAILURE: 'DELETE_CHARACTER_FAILURE',

  FETCH_CHARACTER_RESOURCES_START: 'FETCH_CHARACTER_RESOURCES_START',
  FETCH_CHARACTER_RESOURCES_SUCCESS: 'FETCH_CHARACTER_RESOURCES_SUCCESS',
  FETCH_CHARACTER_RESOURCES_FAILURE: 'FETCH_CHARACTER_RESOURCES_FAILURE',

  CREATE_CHARACTER_RESOURCE_START: 'CREATE_CHARACTER_RESOURCE_START',
  CREATE_CHARACTER_RESOURCE_SUCCESS: 'CREATE_CHARACTER_RESOURCE_SUCCESS',
  CREATE_CHARACTER_RESOURCE_FAILURE: 'CREATE_CHARACTER_RESOURCE_FAILURE',

  UPDATE_CHARACTER_RESOURCE_START: 'UPDATE_CHARACTER_RESOURCE_START',
  UPDATE_CHARACTER_RESOURCE_SUCCESS: 'UPDATE_CHARACTER_RESOURCE_SUCCESS',
  UPDATE_CHARACTER_RESOURCE_FAILURE: 'UPDATE_CHARACTER_RESOURCE_FAILURE',

  DELETE_CHARACTER_RESOURCE_START: 'DELETE_CHARACTER_RESOURCE_START',
  DELETE_CHARACTER_RESOURCE_SUCCESS: 'DELETE_CHARACTER_RESOURCE_SUCCESS',
  DELETE_CHARACTER_RESOURCE_FAILURE: 'DELETE_CHARACTER_RESOURCE_FAILURE',
};

export default CharacterActionTypes;
