const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  CREATE_SHEET_START: 'CREATE_NEW_CHARACTER_SHEET_START',
  CREATE_SHEET_SUCCESS: 'CREATE_NEW_CHARACTER_SHEET_SUCCESS',
  CREATE_SHEET_FAILURE: 'CREATE_NEW_CHARACTER_SHEET_FAILURE',

  DELETE_SHEET_START: 'DELETE_CHARACTER_SHEET_START',
  DELETE_SHEET_SUCCESS: 'DELETE_CHARACTER_SHEET_SUCCESS',
  DELETE_SHEET_FAILURE: 'DELETE_CHARACTER_SHEET_FAILURE',
};

export default UserActionTypes;
