const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  FETCH_SHEETS_FOR_USER_START: 'FETCH_SHEETS_FOR_USER_START',
  FETCH_SHEETS_FOR_USER_SUCCESS: 'FETCH_SHEETS_FOR_USER_SUCCESS',
  FETCH_SHEETS_FOR_USER_FAILURE: 'FETCH_SHEETS_FOR_USER_FAILURE',

  CREATE_SHEET_FOR_USER_START: 'CREATE_SHEET_FOR_USER_START',
  CREATE_SHEET_FOR_USER_SUCCESS: 'CREATE_SHEET_FOR_USER_SUCCESS',
  CREATE_SHEET_FOR_USER_FAILURE: 'CREATE_SHEET_FOR_USER_FAILURE',
};

export default UserActionTypes;
