const AppActionTypes = {
  SET_MODAL: 'SET_MODAL',
  SET_NESTED_MODAL: 'SET_NESTED_MODAL',
  SET_SLIDE_OVER: 'SET_SLIDE_OVER',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION',
  SET_ALERT: 'SET_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',
};

export default AppActionTypes;
