const AppActionTypes = {
  SET_MODAL: 'SET_MODAL',
  SET_SLIDE_OVER: 'SET_SLIDE_OVER',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION',
};

export default AppActionTypes;
