const ResourceActionTypes = {
  FETCH_RESOURCE_START: 'FETCH_RESOURCE_START',
  FETCH_RESOURCE_SUCCESS: 'FETCH_RESOURCE_SUCCESS',
  FETCH_RESOURCE_FAILURE: 'FETCH_RESOURCE_FAILURE',
};

export default ResourceActionTypes;
